apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: example1
 name: example1
spec:
 replicas: 1
 selector:
   matchLabels:
     app: example1
 template:
   metadata:
     labels:
       app: example1
   spec:
     containers:
     - image: nginx:latest
       name: nginx
       resources:
         requests:
           cpu: 100m
           memory: 128Mi
         optional:
         limits:
           cpu: 500m
           memory: 256Mi
       ports:
       - containerPort: 80
         name: nginx
