kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta3
        controllerManager:
          extraArgs:
            horizontal-pod-autoscaler-sync-period: "5s"
            # horizontal-pod-autoscaler-downscale-stabilization: "60s"